### ISSUE TITLE
header template

### ISSUE THREAD

**Issue by willy800510** [willy800510/logoWeb#10]
header 的 bg-color 選擇 transparent 且有使用backdrop-filter: blur(5px) 來達到下層模糊
>header.css
```css
header {
    background-color: transparent;
    backdrop-filter: blur(5px);
    -webkit-backdrop-filter: blur(5px);
  }
```
但在瀏覽器適用性上 firefox 要透過自身瀏覽器的設定更改才能讓backdrop-filter: blur作用
最快的方法就是header給底色（原先設計也是有透明度的底色）
但加入想要達到backdrop-filter: blur的效果，不知道有無其他方式？
